# Generated by Django 3.2.4 on 2023-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('link', models.TextField(verbose_name='link')),
                ('img', models.ImageField(upload_to='uploads/', verbose_name='img')),
                ('desc', models.TextField(verbose_name='desc')),
                ('all_skills', models.TextField(verbose_name='all_skills')),
                ('experience', models.IntegerField(verbose_name='experience')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('price_per_hour', models.IntegerField(verbose_name='price_per_hour')),
                ('reviews_num', models.IntegerField(verbose_name='reviews_num')),
                ('tutor_id', models.IntegerField(verbose_name='tutor_id')),
                ('education', models.TextField(verbose_name='education')),
                ('level_of_skills', models.TextField(verbose_name='level_of_skills')),
            ],
        ),
    ]
